version: '3'

services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    ports:
      - 3306:3306

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    container_name: dynamodb
    ports:
      - 8000:8000

  redis:
    restart: always
    container_name: redis
    image: redis:6.0-alpine
    ports:
      - 6379:6379
